### ISSUE TITLE
The app crashes, when the public key is not correct

### ISSUE THREAD

**Issue by hysapp** [myketstore/myket-billing-client#6]
I deliberately changed the public key for testing to avoid possible errors. In this case, an exception occurs that cannot be handled and the app crashes.

` java.lang.IllegalArgumentException: ir.myket.billingclient.util.Base64DecoderException: Bad Base64 input character at 0: 46(decimal)
 	at ir.myket.billingclient.util.Security.generatePublicKey(Security.java:85)
 	at ir.myket.billingclient.util.Security.verifyPurchase(Security.java:62)
 	at ir.myket.billingclient.IabHelper.queryPurchases(IabHelper.java:575)
 	at ir.myket.billingclient.IabHelper.queryInventory(IabHelper.java:409)
 	at ir.myket.billingclient.IabHelper.queryInventory(IabHelper.java:386)
 	at ir.myket.billingclient.IabHelper$3.run(IabHelper.java:453)
 	at java.lang.Thread.run(Thread.java:929)
 Caused by: ir.myket.billingclient.util.Base64DecoderException: Bad Base64 input character at 0: 46(decimal)
 	at ir.myket.billingclient.util.Base64.decode(Base64.java:557)
 	at ir.myket.billingclient.util.Base64.decode(Base64.java:485)
 	at ir.myket.billingclient.util.Base64.decode(Base64.java:431)
 	at ir.myket.billingclient.util.Security.generatePublicKey(Security.java:75)
 	at ir.myket.billingclient.util.Security.verifyPurchase(Security.java:62) 
 	at ir.myket.billingclient.IabHelper.queryPurchases(IabHelper.java:575) 
 	at ir.myket.billingclient.IabHelper.queryInventory(IabHelper.java:409) 
 	at ir.myket.billingclient.IabHelper.queryInventory(IabHelper.java:386) 
 	at ir.myket.billingclient.IabHelper$3.run(IabHelper.java:453) 
                                                                                                    	at java.lang.Thread.run(Thread.java:929)  `

**Comment by komeilkamal** [comment]
Your RSA Public key must base64 decodable.
For what test do you need to enter the wrong key?  The public key is hard-coded placed in your code.

**Comment by hysapp** [comment]
I do not hardcode the public key due to increased security. And the key is generated on the server side. A human error may crash the app of thousands of users!

**Comment by hysapp** [comment]
> Your RSA Public key must base64 decodable. For what test do you need to enter the wrong key? The public key is hard-coded placed in your code.


I do not hardcode the public key due to increased security. And the key is generated on the server side. A human error may crash the app of thousands of users!

**Comment by komeilkamal** [comment]
There is no reason to not hardcode the public-key. It's public and the private-key is located on the Myket server. Pay attention that this pair-keys is created once for your app on Myket server and you should not generate it on your server. You just need to use the RSA public-key you got from the Myket Developers Panel in your app.
